service: telephonist-csharp
provider:
  name: aws
  profile: private
  region: eu-central-1
  runtime: dotnetcore1.0
package:
  artifact: bin/release/netcoreapp1.0/deploy-package.zip
functions:
  GetDetailsForCurrentOnCallOperator:
    handler: TelephonistServiceCSharp::Telephonist.ScheduleAPI::GetDetailsForCurrentOnCallOperator
    environment:
      PAGER_DUTY_DOMAIN: ${file(.local-keys.yml):PAGER_DUTY_DOMAIN}
      PAGER_DUTY_API_KEY: ${file(.local-keys.yml):PAGER_DUTY_API_KEY}
      PAGER_DUTY_SCHEDULE_ID: ${file(.local-keys.yml):PAGER_DUTY_SCHEDULE_ID}
